# Configure Cloudflare Worker

name = 'hosting-cloudflare-worker'
compatibility_date = "2025-05-26"

[build]
command = "./build.sh"

[assets]
directory = "./builds/site"
not_found_handling = "404-page"
