name: Scheduled File Update

on:
  workflow_dispatch:
  schedule:
    - cron: '37 21 * * *'

jobs:
  update-file:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update file with current timestamp
        run: |
          FILE_TO_UPDATE="updated_log.txt"
          echo "$(date '+%Y-%m-%d %H:%M:%S')" > "${FILE_TO_UPDATE}"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Automated: Update ${FILE_TO_UPDATE} via scheduled job"
          git push
